# --------------------------------------------------------
# 2014-09-27 20:00

ALTER TABLE `traders` ADD `craft_id` INT UNSIGNED NULL AFTER `location_id`, ADD INDEX (`craft_id`) ;
ALTER TABLE `traders` ADD INDEX(`location_id`);
ALTER TABLE `traders` ADD FOREIGN KEY (`location_id`) REFERENCES `elite_trader`.`locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `traders` ADD FOREIGN KEY (`craft_id`) REFERENCES `elite_trader`.`craft`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `prices` CHANGE `price_buy` `price_buy` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL, CHANGE `price_sell` `price_sell` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `craft_locations` CHANGE `price_buy` `price_buy` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL, CHANGE `price_sell` `price_sell` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `craft` ADD `range_min` FLOAT NULL AFTER `speed`, ADD `range_max` FLOAT NULL AFTER `range_min`;
ALTER TABLE `craft` CHANGE `range_min` `range_min` DECIMAL(10,2) NULL DEFAULT NULL, CHANGE `range_max` `range_max` DECIMAL(10,2) NULL DEFAULT NULL;

ALTER TABLE `traders` DROP `settings_json`;
ALTER TABLE `traders` ADD `hops` INT UNSIGNED NULL AFTER `pwd`, ADD `range` DECIMAL(10,2) UNSIGNED NULL AFTER `hops`;
ALTER TABLE `craft` CHANGE `range_min` `range_min` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL, CHANGE `range_max` `range_max` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `craft` CHANGE `speed` `speed` INT(11) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `traders` ADD `is_editor` BOOLEAN NULL DEFAULT TRUE AFTER `craft_id`;

ALTER TABLE `traders` ADD `hops` INT UNSIGNED NULL AFTER `pwd`, ADD `distance_max` DECIMAL(10,2) UNSIGNED NULL AFTER `hops`;

ALTER TABLE `traders` CHANGE `ts` `ts` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `roads` CHANGE `ts` `ts` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `prices` CHANGE `ts` `ts` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `locations` CHANGE `ts` `ts` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `goods` CHANGE `ts` `ts` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `craft` CHANGE `ts` `ts` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `goods` DROP FOREIGN KEY `goods_ibfk_1`;
ALTER TABLE `goods` ADD CONSTRAINT `goods_ibfk_1` FOREIGN KEY (`trader_id`) REFERENCES `elite_trader`.`traders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `craft` DROP FOREIGN KEY `craft_ibfk_1`;
ALTER TABLE `craft` ADD CONSTRAINT `craft_ibfk_1` FOREIGN KEY (`trader_id`) REFERENCES `elite_trader`.`traders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `locations` DROP FOREIGN KEY `locations_ibfk_1`;
ALTER TABLE `locations` ADD CONSTRAINT `locations_ibfk_1` FOREIGN KEY (`trader_id`) REFERENCES `elite_trader`.`traders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `roads` DROP FOREIGN KEY `roads_ibfk_1`;
ALTER TABLE `roads` ADD CONSTRAINT `roads_ibfk_1` FOREIGN KEY (`trader_id`) REFERENCES `elite_trader`.`traders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;